version: '3'

services:
  db:
    image: postgres:alpine
    container_name: social_network_db 
    env_file:
      - ./.env
    ports:
      - "5457:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  app:
    build: .
    command: bash -c "/app/runserver.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: social_network_app

volumes:
  postgres_data:
